[package]
name = "realtime-status-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
fred = { version = "^10", features = ["subscriber-client"] }
clap = { version = "^4.5", features = ["derive"] }
anyhow = "^1"
tokio = { version = "^1", features = ["full"] }